---
title: "BMIN503/EPID600 Project Template"
author: "Shaiza Sinha"
output: 
  html_document:
    theme: paper 
    highlight: tango
---


***
Use this template to complete your project throughout the course. Your Final Project presentation will be based on the contents of this document. Replace the title/name above and text below with your own, but keep the headers. Feel free to change the theme and other display settings, but this is not required. Include a link to your final project GitHub repository.


### Overview
Give a brief a description of your project and its goal(s), what data you are using to complete it, and what two faculty/staff in different fields you have spoken to about your project with a brief summary of what you learned from each person. 

>TITLE: Pennsylvania Assessment of Social-Demographic Characteristics on Receiving Adequate Prenatal Care for 2019-2020

> ABTRACT: This project utilized data obtained by the Center for Disease WONDER Database, which follows an ad-hoc query system for "the analysis of public health data." The study aimed to identify the relationship of demographic characterisitcs on recieving adequete prenatal care services for undocumented immigrants *VALUE NEEDED HERE(n=)

>TEAM DETAILS: This project was extensively discussed with the data team  with the City of Philadelphia, Department of Public Health, in the division of Maternal, Child,and  Family Health Division. Names, MP and AM, have been initialized for the privacy of the team. (Names can be found in the discussion comments of the Canva Submission ). The team consisted of a data analyst specialist (MP) and the city's medical chief officer MD, MPP. MP was involved in assisting the development of the statistical approach. In meetings we discussed what statistical approach would be best for the data set. MP recommended using a multiple linear regression and determining aptly provided prenatal services using a dichtomous approach to simplify data interpretation. AM acted in a supervisionary role as medical chief officer for guiding selection the of social factors for assessment and identifying the social importantance of the project. There is currently  very little limited understanding of migrant and undocumented health and their respective health outcomes in Philadelphia.

>This Data is intended to be used with an altered dataset to utilize the findings to identify potential social barriers and geographic disparities using geospatial distribution. The information from this project will ideally be a part of  a larger strategy proposal acting as a City Landscape Assesment for the development of a be healthcare service delivery model for prenatal care for migrant and undocumented immigrants. 


>https://github.com/shaizas/BMIN503_Final_Project

### Introduction 
Describe the problem addressed, its, and some background to motivate the problem. Explain why your problem is interdisciplinary, what fields can contribute to its understanding, and incorporate background related to what you learned from meeting with faculty/staff.

>Comprehensive prenatal care has been shown to lead to improved health outcomes for both mothers and newborns.1 If sought early in a birthing person’s pregnancy, antenatal care can be used as an effective preventative measure for adverse health outcomes, such as severe maternal morbidity and low neonatal birth weight.2,3 Services are typically established within the first six to eight weeks of pregnancy, following twelve to fifteen visits in total after the initial visit.4 The current model practiced within the United States recommends that patients visit monthly until twenty-eight weeks, bi-weekly until thirty-two weeks, and weekly until delivery.4 Visits are critical to promoting a safe delivery by effectively monitoring the patient's progress and development of the fetus. Healthcare providers are responsible for providing supportive care through medical screenings, lab testing for birth anomalies, image testing, and education (parenting, pregnancy materials, infant feeding).2 Services often include psychosocial support to address substance use, resources for domestic violence, mental health services, avenues for financial aid, and nutritional needs.4

>The State of Pennsylvania has a varied demographic landscape, with individuals belonging to diverse social and cultural backgrounds that may inadvertently hinder access to quality prenatal care. In 2020, 77.5% of birthing persons received prenatal care. However, in the City of Philadelphia specifically, only 52% of birthing persons sought care within the first trimester in Philadelphia, which is comparatively more than the state and the national average of 77%.5,6 Native and Black individuals are two to three times more likely to die from a pregnancy-related cause compared to white populations. These statistics capture the challenges and elucidate potential barriers patients may face to receiving adequate maternal and child care in Pennsylvania.  Common barriers include financial constraints, transportation access, lifestyle limitations (childcare, paid time off from work), and overall distrust of the medical field stemming from perceived discrimination and cultural practice.7 Social factors such as race, age, education levels, socio-economic status have been shown to have associations with receiving adequate prenatal care among migrant populations.  

> Identifying currently underserved populations receiving inadequate access to prenatal services is critical for equitably promoting better maternal and child outcomes. However, there is very limited research in identifying potential social barriers migrant populations face in Pennsylvania.

>This project aims to determine the relationship between demographic characteristics on receiving adequate prenatal care services using a multiple linear regression model.  *This project specifically will assess the interaction of race, age, and education level, with receiving adequate prenatal care (Y/N: 10 visits made during pregnancy) in migrant populations (maternal birth country variable) * 

>Evaluations will require an intersectional approach for analysis. Biomedical informatics can be an effective tool for statistical analysis to identify the gravity of public health issues. The results can be helpful to many stakeholders within the maternal and child health sector, from community organizations to large-scale hospital systems. An improved understanding of prenatal care adequacy is critical for identifying barriers to eliminating current issues through robust program implementation. 

>The findings of this project will be incorporated into a larger strategy proposal for the City of Philadelphia, which aims to propose a series of recommendations that the Department of Public Health can modify for implementation in Philadelphia to improve antenatal services to undocumented residents. 

### Methods
Describe the data used and general methodological approach. Subsequently, incorporate full R code necessary to retrieve and clean data, and perform analysis. Be sure to include a description of code so that others (including your future self) can understand what you are doing and why. 

>LITERATURE METHODS: The quantitative assessment utilized data from the CDC’S WONDER Database, which collects information on an ad-hoc basis for a variety of public health variables and demographic characteristics. The newest dataset was drawn from the Natality online database, which is compiled of data primarily obtained from birth certificates issued in 2016 to 2020 (most updated version) 

>The actual health outcomes of migrant populations are largely unknown within the State of Pennsylvania. The results were conducted to assess if different demographic characteristics may have an impact on a migrant birthing person’s access to prenatal services.  In this analysis, a multiple linear regression was conducted using R Studio. The code was thoroughly assessed by a data team by the City and the University of Pennsylvania. 

>Race, age, and education level were aggregated to determine if adequate prenatal care had been provided to migrant populations using the Kotelchuck Index (Y/N) in a dichotomous format. Adequate prenatal care is determined by two variables obtained from birth certificates which include when prenatal care was started and the number of prenatal visits until delivery. On average, a patient will complete twelve to fifteen prenatal visits in total. Typically, adequate care is achieved if a patient has completed 80% or ten appointments. While the Kotelchuck Index cannot determine the quality of prenatal care or accurately be applied for high-risk pregnancies, it remains a commonly utilized method for determining if prenatal care services have been adequately provided. Using the ACOG guidelines and for the simplicity of this project, adequate prenatal care was determined if a patient had more than or equal to ten visits <=10. 

>Question: How are migrant populations
>Independent: Received adequate prenatal care (10+ visits)
>Dependent variable: race, age, education level
>Population: Migrant Populations in Pennsylvania in 2019-2022 (maternal birth country, excluding the United States)
>Control: Pennsylvania US Citizens

>CODING METHODS: 


### Results
Describe your results and include relevant tables, plots, and code/comments used to obtain them. End with a brief conclusion of your findings related to the question you set out to address. You can include references if you'd like, but this is not required.
